[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/heartbeat"
healthcheckTimeout = 60
healthcheckInterval = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = { SSL_VERIFY = "false", CORS_ORIGINS = "*" }
